///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The After_adding_bespoke_product_I_expect_to_be_directed_to_the_add_new_quote_screen_showing_quote recording.
    /// </summary>
    [TestModule("1ee65b38-ab6b-45c3-9f60-6ab7cfd1c8cf", ModuleType.Recording, 1)]
    public partial class After_adding_bespoke_product_I_expect_to_be_directed_to_the_add_new_quote_screen_showing_quote : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static After_adding_bespoke_product_I_expect_to_be_directed_to_the_add_new_quote_screen_showing_quote instance = new After_adding_bespoke_product_I_expect_to_be_directed_to_the_add_new_quote_screen_showing_quote();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public After_adding_bespoke_product_I_expect_to_be_directed_to_the_add_new_quote_screen_showing_quote()
        {
            ExWidth_mm = "";
            ExDepth_mm = "";
            ExHeight_mm = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static After_adding_bespoke_product_I_expect_to_be_directed_to_the_add_new_quote_screen_showing_quote Instance
        {
            get { return instance; }
        }

#region Variables

        string _ExWidth_mm;

        /// <summary>
        /// Gets or sets the value of variable ExWidth_mm.
        /// </summary>
        [TestVariable("3ddd71d4-2474-4390-9744-22bed1712726")]
        public string ExWidth_mm
        {
            get { return _ExWidth_mm; }
            set { _ExWidth_mm = value; }
        }

        string _ExDepth_mm;

        /// <summary>
        /// Gets or sets the value of variable ExDepth_mm.
        /// </summary>
        [TestVariable("6135bb6b-b7af-43b8-9b8b-5c78ff8264f2")]
        public string ExDepth_mm
        {
            get { return _ExDepth_mm; }
            set { _ExDepth_mm = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ExHeight_mm.
        /// </summary>
        [TestVariable("7a162813-1ade-47b1-b159-c22a0cb82d18")]
        public string ExHeight_mm
        {
            get { return repo.ExHeight_mm; }
            set { repo.ExHeight_mm = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'MyHafelePortal'.", repo.MyHafelePortal.SelfInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(1));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.BespokeDrawers' at Center.", repo.MyHafelePortal.BespokeDrawersInfo, new RecordItemIndex(2));
            repo.MyHafelePortal.BespokeDrawers.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'MyHafelePortal.StartNewQuote'.", repo.MyHafelePortal.StartNewQuoteInfo, new RecordItemIndex(3));
            repo.MyHafelePortal.StartNewQuote.PerformClick();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.StartNewQuote' at Center.", repo.MyHafelePortal.StartNewQuoteInfo, new RecordItemIndex(4));
            //repo.MyHafelePortal.StartNewQuote.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddProduct' at Center.", repo.MyHafelePortal.AddProductInfo, new RecordItemIndex(5));
            repo.MyHafelePortal.AddProduct.Click();
            Delay.Milliseconds(200);
            
            // New Module called Timber Drawer
            Report.Log(ReportLevel.Info, "Section", "New Module called Timber Drawer", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.TimberDrawer' at Center.", repo.MyHafelePortal.TimberDrawerInfo, new RecordItemIndex(7));
            repo.MyHafelePortal.TimberDrawer.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Continue' at Center.", repo.MyHafelePortal.ContinueInfo, new RecordItemIndex(8));
            repo.MyHafelePortal.Continue.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.MoreInfo' at Center.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.MoreInfoInfo, new RecordItemIndex(9));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.MoreInfo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://qmy.hafele.co.uk/assets/img/quotes/btd/moreinfo/drawer_dimensions.png') on item 'MyHafelePortal.Dimensions'.", repo.MyHafelePortal.DimensionsInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.MyHafelePortal.DimensionsInfo, "Src", "https://qmy.hafele.co.uk/assets/img/quotes/btd/moreinfo/drawer_dimensions.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Close' at Center.", repo.MyHafelePortal.CloseInfo, new RecordItemIndex(11));
            repo.MyHafelePortal.Close.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text' at 95;20.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_TextInfo, new RecordItemIndex(12));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text.Click("95;20");
            Delay.Milliseconds(200);
            
            // Dimensions
            Report.Log(ReportLevel.Info, "Section", "Dimensions", new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ExWidth_mm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_TextInfo, new RecordItemIndex(14));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text.PressKeys(ExWidth_mm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text' at 27;22.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_TextInfo, new RecordItemIndex(15));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text.Click("27;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ExDepth_mm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_TextInfo, new RecordItemIndex(16));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text.PressKeys(ExDepth_mm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text' at 21;21.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_TextInfo, new RecordItemIndex(17));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text.Click("21;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ExHeight_mm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_TextInfo, new RecordItemIndex(18));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text.PressKeys(ExHeight_mm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(19));
            Delay.Duration(2000, false);
            
            // Material
            Report.Log(ReportLevel.Info, "Section", "Material", new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.ImgTagPly' at 49;60.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.ImgTagPlyInfo, new RecordItemIndex(21));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.ImgTagPly.Click("49;60");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Thickness' at 215;20.", repo.MyHafelePortal.ThicknessInfo, new RecordItemIndex(22));
            repo.MyHafelePortal.Thickness.Click("215;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Chrome.Pane' at 187;27.", repo.Chrome.PaneInfo, new RecordItemIndex(23));
            repo.Chrome.Pane.Click("187;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.DivTagDot' at Center.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.DivTagDotInfo, new RecordItemIndex(24));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.DivTagDot.Click();
            Delay.Milliseconds(200);
            
            // Additional lnformation
            Report.Log(ReportLevel.Info, "Section", "Additional lnformation", new RecordItemIndex(25));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductRe' at 366;20.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductReInfo, new RecordItemIndex(26));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductRe.Click("366;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'The quick brown fox jumped over the lazy dog' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductRe'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductReInfo, new RecordItemIndex(27));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductRe.PressKeys("The quick brown fox jumped over the lazy dog");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductRe'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductReInfo, new RecordItemIndex(28));
            Validate.Exists(repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.PleaseSpecifyAnyAdditionalProductReInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.SaveProductAndExit' at 79;7.", repo.MyHafelePortal.SaveProductAndExitInfo, new RecordItemIndex(29));
            repo.MyHafelePortal.SaveProductAndExit.Click("79;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyHafelePortal.QuoteSummary'.", repo.MyHafelePortal.QuoteSummaryInfo, new RecordItemIndex(30));
            Validate.Exists(repo.MyHafelePortal.QuoteSummaryInfo);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MyHafelePortal.QuoteSummary, false, new RecordItemIndex(31));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.CancelQuote' at Center.", repo.MyHafelePortal.CancelQuoteInfo, new RecordItemIndex(32));
            repo.MyHafelePortal.CancelQuote.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AreYouSure_CancelQuote' at Center.", repo.MyHafelePortal.AreYouSure_CancelQuoteInfo, new RecordItemIndex(33));
            repo.MyHafelePortal.AreYouSure_CancelQuote.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
