///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD10_Add_Delivery_Addrerss recording.
    /// </summary>
    [TestModule("ebe72804-3520-486a-8583-4600f7f8f4de", ModuleType.Recording, 1)]
    public partial class BTD10_Add_Delivery_Addrerss : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD10_Add_Delivery_Addrerss instance = new BTD10_Add_Delivery_Addrerss();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD10_Add_Delivery_Addrerss()
        {
            ContactName = "";
            TelephoneNumber = "";
            CompanyName = "";
            AddressLine1 = "";
            AddressLine2 = "";
            Town_City = "";
            County = "";
            Gmail_Address = "";
            YourReference = "";
            Postcode = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD10_Add_Delivery_Addrerss Instance
        {
            get { return instance; }
        }

#region Variables

        string _ContactName;

        /// <summary>
        /// Gets or sets the value of variable ContactName.
        /// </summary>
        [TestVariable("d8a71c37-9bc9-4678-9cdb-6c2c8ca823ff")]
        public string ContactName
        {
            get { return _ContactName; }
            set { _ContactName = value; }
        }

        string _TelephoneNumber;

        /// <summary>
        /// Gets or sets the value of variable TelephoneNumber.
        /// </summary>
        [TestVariable("71712e23-6736-4492-848b-3d6a9eae8cdd")]
        public string TelephoneNumber
        {
            get { return _TelephoneNumber; }
            set { _TelephoneNumber = value; }
        }

        string _CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CompanyName.
        /// </summary>
        [TestVariable("34a5c9e5-5c40-4617-bb1d-9b0fe8a3fe34")]
        public string CompanyName
        {
            get { return _CompanyName; }
            set { _CompanyName = value; }
        }

        string _AddressLine1;

        /// <summary>
        /// Gets or sets the value of variable AddressLine1.
        /// </summary>
        [TestVariable("84360468-9695-42b5-b4b2-0aab03f158d3")]
        public string AddressLine1
        {
            get { return _AddressLine1; }
            set { _AddressLine1 = value; }
        }

        string _AddressLine2;

        /// <summary>
        /// Gets or sets the value of variable AddressLine2.
        /// </summary>
        [TestVariable("773525d2-ae8b-4e8a-b2e5-19158b12c894")]
        public string AddressLine2
        {
            get { return _AddressLine2; }
            set { _AddressLine2 = value; }
        }

        string _Town_City;

        /// <summary>
        /// Gets or sets the value of variable Town_City.
        /// </summary>
        [TestVariable("1bf6d3b4-6a40-48be-86bb-4344914b7e9a")]
        public string Town_City
        {
            get { return _Town_City; }
            set { _Town_City = value; }
        }

        string _County;

        /// <summary>
        /// Gets or sets the value of variable County.
        /// </summary>
        [TestVariable("f8e063b2-996a-44a5-b735-37b6b9c48ccc")]
        public string County
        {
            get { return _County; }
            set { _County = value; }
        }

        string _Gmail_Address;

        /// <summary>
        /// Gets or sets the value of variable Gmail_Address.
        /// </summary>
        [TestVariable("f9b8946c-be51-4801-8593-88493d47d6f7")]
        public string Gmail_Address
        {
            get { return _Gmail_Address; }
            set { _Gmail_Address = value; }
        }

        string _YourReference;

        /// <summary>
        /// Gets or sets the value of variable YourReference.
        /// </summary>
        [TestVariable("1e9bb407-bcdd-4f4e-aa48-62649b7a6965")]
        public string YourReference
        {
            get { return _YourReference; }
            set { _YourReference = value; }
        }

        string _Postcode;

        /// <summary>
        /// Gets or sets the value of variable Postcode.
        /// </summary>
        [TestVariable("a9697a67-cb46-460b-891e-a56ffe7bfbc7")]
        public string Postcode
        {
            get { return _Postcode; }
            set { _Postcode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddDeliveryAddress' at Center.", repo.MyHafelePortal.AddDeliveryAddressInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.AddDeliveryAddress.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ContactName' with focus on 'MyHafelePortal.DeliveryContact_ContactName'.", repo.MyHafelePortal.DeliveryContact_ContactNameInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.DeliveryContact_ContactName.PressKeys(ContactName);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryContact_ContactName'.", repo.MyHafelePortal.DeliveryContact_ContactNameInfo, new RecordItemIndex(2));
                Validate.Exists(repo.MyHafelePortal.DeliveryContact_ContactNameInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TelephoneNumber' with focus on 'MyHafelePortal.DeliveryContact_TelephoneNumber'.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(3));
            repo.MyHafelePortal.DeliveryContact_TelephoneNumber.PressKeys(TelephoneNumber);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryContact_TelephoneNumber'.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(4));
                Validate.Exists(repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_AddAddressManually' at Center.", repo.MyHafelePortal.DeliveryAddress_AddAddressManuallyInfo, new RecordItemIndex(5));
            repo.MyHafelePortal.DeliveryAddress_AddAddressManually.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CompanyName' with focus on 'MyHafelePortal.DeliveryAddress_CompanyName'.", repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, new RecordItemIndex(6));
            repo.MyHafelePortal.DeliveryAddress_CompanyName.PressKeys(CompanyName);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_CompanyName'.", repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, new RecordItemIndex(7));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine1' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine1'.", repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, new RecordItemIndex(8));
            repo.MyHafelePortal.DeliveryAddress_AddressLine1.PressKeys(AddressLine1);
            Delay.Milliseconds(100);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_AddressLine1'.", repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, new RecordItemIndex(9));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine2' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine2'.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(10));
            repo.MyHafelePortal.DeliveryAddress_AddressLine2.PressKeys(AddressLine2);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_AddressLine2'.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(11));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Town_City' with focus on 'MyHafelePortal.DeliveryAddress_TownCity'.", repo.MyHafelePortal.DeliveryAddress_TownCityInfo, new RecordItemIndex(12));
            repo.MyHafelePortal.DeliveryAddress_TownCity.PressKeys(Town_City);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_TownCity'.", repo.MyHafelePortal.DeliveryAddress_TownCityInfo, new RecordItemIndex(13));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_TownCityInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$County' with focus on 'MyHafelePortal.DeliveryAddress_County'.", repo.MyHafelePortal.DeliveryAddress_CountyInfo, new RecordItemIndex(14));
            repo.MyHafelePortal.DeliveryAddress_County.PressKeys(County);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_County'.", repo.MyHafelePortal.DeliveryAddress_CountyInfo, new RecordItemIndex(15));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_CountyInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(15)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Postcode' with focus on 'MyHafelePortal.DeliveryAddress_Postcode'.", repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, new RecordItemIndex(16));
            repo.MyHafelePortal.DeliveryAddress_Postcode.PressKeys(Postcode);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_Postcode'.", repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, new RecordItemIndex(17));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddDeliveryAddressButton' at Center.", repo.MyHafelePortal.AddDeliveryAddressButtonInfo, new RecordItemIndex(18));
            repo.MyHafelePortal.AddDeliveryAddressButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_EmailAddress' at Center.", repo.MyHafelePortal.DeliveryAddress_EmailAddressInfo, new RecordItemIndex(19));
            repo.MyHafelePortal.DeliveryAddress_EmailAddress.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Gmail_Address' with focus on 'MyHafelePortal.DeliveryAddress_EmailAddress'.", repo.MyHafelePortal.DeliveryAddress_EmailAddressInfo, new RecordItemIndex(20));
            repo.MyHafelePortal.DeliveryAddress_EmailAddress.PressKeys(Gmail_Address);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_YourReference' at Center.", repo.MyHafelePortal.DeliveryAddress_YourReferenceInfo, new RecordItemIndex(21));
            repo.MyHafelePortal.DeliveryAddress_YourReference.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$YourReference' with focus on 'MyHafelePortal.DeliveryAddress_YourReference'.", repo.MyHafelePortal.DeliveryAddress_YourReferenceInfo, new RecordItemIndex(22));
            repo.MyHafelePortal.DeliveryAddress_YourReference.PressKeys(YourReference);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.PlaceOrder_Button'.", repo.MyHafelePortal.PlaceOrder_ButtonInfo, new RecordItemIndex(23));
            repo.MyHafelePortal.PlaceOrder_Button.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.PlaceOrder_Button' at Center.", repo.MyHafelePortal.PlaceOrder_ButtonInfo, new RecordItemIndex(24));
            repo.MyHafelePortal.PlaceOrder_Button.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyHafelePortal.Before_you_place_your_order_DialogueBox'.", repo.MyHafelePortal.Before_you_place_your_order_DialogueBoxInfo, new RecordItemIndex(25));
            Validate.Exists(repo.MyHafelePortal.Before_you_place_your_order_DialogueBoxInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MyHafelePortal.Before_you_place_your_order_DialogueBox, false, new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(27));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AggreeAndConfirmOrder_Button' at Center.", repo.MyHafelePortal.AggreeAndConfirmOrder_ButtonInfo, new RecordItemIndex(28));
            repo.MyHafelePortal.AggreeAndConfirmOrder_Button.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1m.", new RecordItemIndex(29));
            Delay.Duration(60000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.ReturnToQuotes_Button' at Center.", repo.MyHafelePortal.ReturnToQuotes_ButtonInfo, new RecordItemIndex(30));
            repo.MyHafelePortal.ReturnToQuotes_Button.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
