///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD10_Add_Delivery_Address_Only recording.
    /// </summary>
    [TestModule("b15a6e94-ec11-44f2-a377-25550eb9693d", ModuleType.Recording, 1)]
    public partial class BTD10_Add_Delivery_Address_Only : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD10_Add_Delivery_Address_Only instance = new BTD10_Add_Delivery_Address_Only();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD10_Add_Delivery_Address_Only()
        {
            ContactName = "";
            TelephoneNumber = "";
            CompanyName = "";
            AddressLine1 = "";
            AddressLine2 = "";
            Town_City = "";
            County = "";
            Postcode = "";
            Gmail_Address = "";
            YourReference = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD10_Add_Delivery_Address_Only Instance
        {
            get { return instance; }
        }

#region Variables

        string _ContactName;

        /// <summary>
        /// Gets or sets the value of variable ContactName.
        /// </summary>
        [TestVariable("6dcf5b35-97d6-4b7e-9466-932deb236f67")]
        public string ContactName
        {
            get { return _ContactName; }
            set { _ContactName = value; }
        }

        string _TelephoneNumber;

        /// <summary>
        /// Gets or sets the value of variable TelephoneNumber.
        /// </summary>
        [TestVariable("02d40a2b-412a-4070-832e-3a915f56f5d0")]
        public string TelephoneNumber
        {
            get { return _TelephoneNumber; }
            set { _TelephoneNumber = value; }
        }

        string _CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CompanyName.
        /// </summary>
        [TestVariable("9b96e0cd-9df1-4045-81f0-892988296e84")]
        public string CompanyName
        {
            get { return _CompanyName; }
            set { _CompanyName = value; }
        }

        string _AddressLine1;

        /// <summary>
        /// Gets or sets the value of variable AddressLine1.
        /// </summary>
        [TestVariable("503935d3-f5e3-4a39-9f3b-f10e522f69de")]
        public string AddressLine1
        {
            get { return _AddressLine1; }
            set { _AddressLine1 = value; }
        }

        string _AddressLine2;

        /// <summary>
        /// Gets or sets the value of variable AddressLine2.
        /// </summary>
        [TestVariable("b9cb925d-2b14-4bcf-8b62-d243ab997ea2")]
        public string AddressLine2
        {
            get { return _AddressLine2; }
            set { _AddressLine2 = value; }
        }

        string _Town_City;

        /// <summary>
        /// Gets or sets the value of variable Town_City.
        /// </summary>
        [TestVariable("c5730fac-fd94-46c4-8beb-e25c6bcffe4e")]
        public string Town_City
        {
            get { return _Town_City; }
            set { _Town_City = value; }
        }

        string _County;

        /// <summary>
        /// Gets or sets the value of variable County.
        /// </summary>
        [TestVariable("01a6e1d0-47ad-4262-8dcf-8dc76ce6b5d9")]
        public string County
        {
            get { return _County; }
            set { _County = value; }
        }

        string _Postcode;

        /// <summary>
        /// Gets or sets the value of variable Postcode.
        /// </summary>
        [TestVariable("e1ecb82a-d616-4561-b1b9-00cfafbb3859")]
        public string Postcode
        {
            get { return _Postcode; }
            set { _Postcode = value; }
        }

        string _Gmail_Address;

        /// <summary>
        /// Gets or sets the value of variable Gmail_Address.
        /// </summary>
        [TestVariable("22f4743b-f488-4d13-8821-571b34a64811")]
        public string Gmail_Address
        {
            get { return _Gmail_Address; }
            set { _Gmail_Address = value; }
        }

        string _YourReference;

        /// <summary>
        /// Gets or sets the value of variable YourReference.
        /// </summary>
        [TestVariable("e545d2a4-16fd-4bba-8484-6dab174e47c7")]
        public string YourReference
        {
            get { return _YourReference; }
            set { _YourReference = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddDeliveryAddress' at Center.", repo.MyHafelePortal.AddDeliveryAddressInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.AddDeliveryAddress.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ContactName' with focus on 'MyHafelePortal.DeliveryContact_ContactName'.", repo.MyHafelePortal.DeliveryContact_ContactNameInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.DeliveryContact_ContactName.PressKeys(ContactName);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryContact_ContactName'.", repo.MyHafelePortal.DeliveryContact_ContactNameInfo, new RecordItemIndex(2));
                Validate.Exists(repo.MyHafelePortal.DeliveryContact_ContactNameInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TelephoneNumber' with focus on 'MyHafelePortal.DeliveryContact_TelephoneNumber'.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(3));
            repo.MyHafelePortal.DeliveryContact_TelephoneNumber.PressKeys(TelephoneNumber);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryContact_TelephoneNumber'.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(4));
                Validate.Exists(repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_AddAddressManually' at Center.", repo.MyHafelePortal.DeliveryAddress_AddAddressManuallyInfo, new RecordItemIndex(5));
            repo.MyHafelePortal.DeliveryAddress_AddAddressManually.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CompanyName' with focus on 'MyHafelePortal.DeliveryAddress_CompanyName'.", repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, new RecordItemIndex(6));
            repo.MyHafelePortal.DeliveryAddress_CompanyName.PressKeys(CompanyName);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_CompanyName'.", repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, new RecordItemIndex(7));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine1' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine1'.", repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, new RecordItemIndex(8));
            repo.MyHafelePortal.DeliveryAddress_AddressLine1.PressKeys(AddressLine1);
            Delay.Milliseconds(100);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_AddressLine1'.", repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, new RecordItemIndex(9));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine2' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine2'.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(10));
            repo.MyHafelePortal.DeliveryAddress_AddressLine2.PressKeys(AddressLine2);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_AddressLine2'.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(11));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Town_City' with focus on 'MyHafelePortal.DeliveryAddress_TownCity'.", repo.MyHafelePortal.DeliveryAddress_TownCityInfo, new RecordItemIndex(12));
            repo.MyHafelePortal.DeliveryAddress_TownCity.PressKeys(Town_City);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_TownCity'.", repo.MyHafelePortal.DeliveryAddress_TownCityInfo, new RecordItemIndex(13));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_TownCityInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$County' with focus on 'MyHafelePortal.DeliveryAddress_County'.", repo.MyHafelePortal.DeliveryAddress_CountyInfo, new RecordItemIndex(14));
            repo.MyHafelePortal.DeliveryAddress_County.PressKeys(County);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_County'.", repo.MyHafelePortal.DeliveryAddress_CountyInfo, new RecordItemIndex(15));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_CountyInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(15)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Postcode' with focus on 'MyHafelePortal.DeliveryAddress_Postcode'.", repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, new RecordItemIndex(16));
            repo.MyHafelePortal.DeliveryAddress_Postcode.PressKeys(Postcode);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.DeliveryAddress_Postcode'.", repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, new RecordItemIndex(17));
                Validate.Exists(repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(17)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddDeliveryAddressButton' at Center.", repo.MyHafelePortal.AddDeliveryAddressButtonInfo, new RecordItemIndex(18));
            repo.MyHafelePortal.AddDeliveryAddressButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
