///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD3_Internal_Cabinet_Dimensions recording.
    /// </summary>
    [TestModule("dab49aaa-e294-4e19-b476-ca5f3ab7ed3d", ModuleType.Recording, 1)]
    public partial class BTD3_Internal_Cabinet_Dimensions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD3_Internal_Cabinet_Dimensions instance = new BTD3_Internal_Cabinet_Dimensions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD3_Internal_Cabinet_Dimensions()
        {
            IntWidth_mm = "";
            IntDepth_mm = "";
            IntHeight_mm = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD3_Internal_Cabinet_Dimensions Instance
        {
            get { return instance; }
        }

#region Variables

        string _IntWidth_mm;

        /// <summary>
        /// Gets or sets the value of variable IntWidth_mm.
        /// </summary>
        [TestVariable("b715e10f-657c-421d-bbe7-bcb14fd01f1a")]
        public string IntWidth_mm
        {
            get { return _IntWidth_mm; }
            set { _IntWidth_mm = value; }
        }

        string _IntDepth_mm;

        /// <summary>
        /// Gets or sets the value of variable IntDepth_mm.
        /// </summary>
        [TestVariable("c546aa0e-983d-4463-bb9e-8b42fc509b1d")]
        public string IntDepth_mm
        {
            get { return _IntDepth_mm; }
            set { _IntDepth_mm = value; }
        }

        string _IntHeight_mm;

        /// <summary>
        /// Gets or sets the value of variable IntHeight_mm.
        /// </summary>
        [TestVariable("70c35906-84a9-4935-94c5-2cb81ee4707b")]
        public string IntHeight_mm
        {
            get { return _IntHeight_mm; }
            set { _IntHeight_mm = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.Dimensions_Internal'.", repo.MyHafelePortal.Dimensions_InternalInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.Dimensions_Internal.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Dimensions_Internal' at Center.", repo.MyHafelePortal.Dimensions_InternalInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.Dimensions_Internal.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text_Internal' at Center.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text_InternalInfo, new RecordItemIndex(3));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text_Internal.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$IntWidth_mm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text_Internal'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text_InternalInfo, new RecordItemIndex(4));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Width_Text_Internal.PressKeys(IntWidth_mm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text' at 27;22.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_TextInfo, new RecordItemIndex(5));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text.Click("27;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$IntDepth_mm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_TextInfo, new RecordItemIndex(6));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Depth_Text.PressKeys(IntDepth_mm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text' at 21;21.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_TextInfo, new RecordItemIndex(7));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text.Click("21;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$IntHeight_mm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_TextInfo, new RecordItemIndex(8));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.Height_Text.PressKeys(IntHeight_mm);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MyHafelePortal.QuoteSummary, false, new RecordItemIndex(10));
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.QuoteSummary'.", repo.MyHafelePortal.QuoteSummaryInfo, new RecordItemIndex(11));
                Validate.Exists(repo.MyHafelePortal.QuoteSummaryInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(12));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
