///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD4_Material_Other recording.
    /// </summary>
    [TestModule("fcf7907e-1706-4cef-8740-c1695402a0df", ModuleType.Recording, 1)]
    public partial class BTD4_Material_Other : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD4_Material_Other instance = new BTD4_Material_Other();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD4_Material_Other()
        {
            Thickness = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD4_Material_Other Instance
        {
            get { return instance; }
        }

#region Variables

        string _Thickness;

        /// <summary>
        /// Gets or sets the value of variable Thickness.
        /// </summary>
        [TestVariable("9fb6f111-ec31-453b-b56d-c36eb9459f66")]
        public string Thickness
        {
            get { return _Thickness; }
            set { _Thickness = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.Material_Other'.", repo.MyHafelePortal.Material_OtherInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.Material_Other.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Material_Other' at Center.", repo.MyHafelePortal.Material_OtherInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.Material_Other.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.CustomMaterialType' at Center.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.CustomMaterialTypeInfo, new RecordItemIndex(2));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.CustomMaterialType.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'elm' with focus on 'MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.CustomMaterialType'.", repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.CustomMaterialTypeInfo, new RecordItemIndex(3));
            repo.MyHafelePortal.HttpsQmyHafeleCoUkQuotesBespoke.CustomMaterialType.PressKeys("elm");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.SelectThickness' at Center.", repo.MyHafelePortal.SelectThicknessInfo, new RecordItemIndex(4));
            repo.MyHafelePortal.SelectThickness.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Thickness' with focus on 'MyHafelePortal.SelectThickness'.", repo.MyHafelePortal.SelectThicknessInfo, new RecordItemIndex(5));
            repo.MyHafelePortal.SelectThickness.PressKeys(Thickness);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
