///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD_Remove_Delivery_Address recording.
    /// </summary>
    [TestModule("732aa3f6-cd04-48f2-95da-690315cb4d33", ModuleType.Recording, 1)]
    public partial class BTD_Remove_Delivery_Address : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD_Remove_Delivery_Address instance = new BTD_Remove_Delivery_Address();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD_Remove_Delivery_Address()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD_Remove_Delivery_Address Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.DeliveryAddress_Remove'.", repo.MyHafelePortal.DeliveryAddress_RemoveInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.DeliveryAddress_Remove.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_Remove' at Center.", repo.MyHafelePortal.DeliveryAddress_RemoveInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.DeliveryAddress_Remove.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.DeliveryAddress_Remove'.", repo.MyHafelePortal.DeliveryAddress_RemoveInfo, new RecordItemIndex(2));
            repo.MyHafelePortal.DeliveryAddress_Remove.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MyHafelePortal.DeliveryAddress_Remove'.", repo.MyHafelePortal.DeliveryAddress_RemoveInfo, new RecordItemIndex(3));
            Validate.Exists(repo.MyHafelePortal.DeliveryAddress_RemoveInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.AreYouSure_DialogueBox'.", repo.MyHafelePortal.AreYouSure_DialogueBoxInfo, new RecordItemIndex(4));
            repo.MyHafelePortal.AreYouSure_DialogueBox.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MyHafelePortal.AreYouSure_DialogueBox, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.YesRemoveAddress' at Center.", repo.MyHafelePortal.YesRemoveAddressInfo, new RecordItemIndex(6));
            repo.MyHafelePortal.YesRemoveAddress.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
