///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD_Order_Confirmation_Email_Validation recording.
    /// </summary>
    [TestModule("5d060e2e-d6c0-4f04-9dc8-9c9191776af3", ModuleType.Recording, 1)]
    public partial class BTD_Order_Confirmation_Email_Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD_Order_Confirmation_Email_Validation instance = new BTD_Order_Confirmation_Email_Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD_Order_Confirmation_Email_Validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD_Order_Confirmation_Email_Validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'GmailInbox.OpenEmail'.", repo.GmailInbox.OpenEmailInfo, new RecordItemIndex(0));
            repo.GmailInbox.OpenEmail.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GmailInbox.OpenEmail' at Center.", repo.GmailInbox.OpenEmailInfo, new RecordItemIndex(1));
            repo.GmailInbox.OpenEmail.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GmailInbox.Open2ndEmailAttachment' at Center.", repo.GmailInbox.Open2ndEmailAttachmentInfo, new RecordItemIndex(3));
            repo.GmailInbox.Open2ndEmailAttachment.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'GmailInbox.ValidateEmailContents'.", repo.GmailInbox.ValidateEmailContentsInfo, new RecordItemIndex(4));
            repo.GmailInbox.ValidateEmailContents.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'GmailInbox.ValidateEmailContents'.", repo.GmailInbox.ValidateEmailContentsInfo, new RecordItemIndex(5));
            Validate.Exists(repo.GmailInbox.ValidateEmailContentsInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.GmailInbox.ValidateEmailContents, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(7));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
