///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BTD_AddManualDeliveryAddress_Within_A_quote recording.
    /// </summary>
    [TestModule("1be8369e-97b1-4f7e-960e-1ba02db88da4", ModuleType.Recording, 1)]
    public partial class BTD_AddManualDeliveryAddress_Within_A_quote : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static BTD_AddManualDeliveryAddress_Within_A_quote instance = new BTD_AddManualDeliveryAddress_Within_A_quote();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BTD_AddManualDeliveryAddress_Within_A_quote()
        {
            ContactName = "";
            TelephoneNumber = "";
            CompanyName = "";
            AddressLine1 = "";
            AddressLine2 = "";
            Town_City = "";
            County = "";
            Postcode = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BTD_AddManualDeliveryAddress_Within_A_quote Instance
        {
            get { return instance; }
        }

#region Variables

        string _ContactName;

        /// <summary>
        /// Gets or sets the value of variable ContactName.
        /// </summary>
        [TestVariable("969c31ad-9ca4-43cb-a975-eaa4b8cee52b")]
        public string ContactName
        {
            get { return _ContactName; }
            set { _ContactName = value; }
        }

        string _TelephoneNumber;

        /// <summary>
        /// Gets or sets the value of variable TelephoneNumber.
        /// </summary>
        [TestVariable("e1b0bdc0-257d-4b1d-b2ef-b84db52a25b7")]
        public string TelephoneNumber
        {
            get { return _TelephoneNumber; }
            set { _TelephoneNumber = value; }
        }

        string _CompanyName;

        /// <summary>
        /// Gets or sets the value of variable CompanyName.
        /// </summary>
        [TestVariable("893ad1f9-f882-4226-a7ec-5331ba0f246a")]
        public string CompanyName
        {
            get { return _CompanyName; }
            set { _CompanyName = value; }
        }

        string _AddressLine1;

        /// <summary>
        /// Gets or sets the value of variable AddressLine1.
        /// </summary>
        [TestVariable("80f0b5f3-94b8-41ac-9284-90c445e9d9bb")]
        public string AddressLine1
        {
            get { return _AddressLine1; }
            set { _AddressLine1 = value; }
        }

        string _AddressLine2;

        /// <summary>
        /// Gets or sets the value of variable AddressLine2.
        /// </summary>
        [TestVariable("fcd9ab17-2e3f-463d-b63d-af052741f521")]
        public string AddressLine2
        {
            get { return _AddressLine2; }
            set { _AddressLine2 = value; }
        }

        string _Town_City;

        /// <summary>
        /// Gets or sets the value of variable Town_City.
        /// </summary>
        [TestVariable("9dd7749e-9b54-4ddb-a53f-33eabcd368e2")]
        public string Town_City
        {
            get { return _Town_City; }
            set { _Town_City = value; }
        }

        string _County;

        /// <summary>
        /// Gets or sets the value of variable County.
        /// </summary>
        [TestVariable("f7570080-d19a-4e28-9841-c3f84f2579a7")]
        public string County
        {
            get { return _County; }
            set { _County = value; }
        }

        string _Postcode;

        /// <summary>
        /// Gets or sets the value of variable Postcode.
        /// </summary>
        [TestVariable("e7fc2f03-cd46-410b-93e7-36306be3ff57")]
        public string Postcode
        {
            get { return _Postcode; }
            set { _Postcode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.AddDeliveryAddress'.", repo.MyHafelePortal.AddDeliveryAddressInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.AddDeliveryAddress.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddDeliveryAddress' at Center.", repo.MyHafelePortal.AddDeliveryAddressInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.AddDeliveryAddress.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryContact_ContactName' at Center.", repo.MyHafelePortal.DeliveryContact_ContactNameInfo, new RecordItemIndex(2));
            repo.MyHafelePortal.DeliveryContact_ContactName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ContactName' with focus on 'MyHafelePortal.DeliveryContact_ContactName'.", repo.MyHafelePortal.DeliveryContact_ContactNameInfo, new RecordItemIndex(3));
            repo.MyHafelePortal.DeliveryContact_ContactName.PressKeys(ContactName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.DeliveryContact_TelephoneNumber'.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(4));
            repo.MyHafelePortal.DeliveryContact_TelephoneNumber.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryContact_TelephoneNumber' at Center.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(5));
            repo.MyHafelePortal.DeliveryContact_TelephoneNumber.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$TelephoneNumber' with focus on 'MyHafelePortal.DeliveryContact_TelephoneNumber'.", repo.MyHafelePortal.DeliveryContact_TelephoneNumberInfo, new RecordItemIndex(6));
            repo.MyHafelePortal.DeliveryContact_TelephoneNumber.PressKeys(TelephoneNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.DeliveryAddress_AddAddressManually'.", repo.MyHafelePortal.DeliveryAddress_AddAddressManuallyInfo, new RecordItemIndex(7));
            repo.MyHafelePortal.DeliveryAddress_AddAddressManually.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_AddAddressManually' at Center.", repo.MyHafelePortal.DeliveryAddress_AddAddressManuallyInfo, new RecordItemIndex(8));
            repo.MyHafelePortal.DeliveryAddress_AddAddressManually.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_CompanyName' at Center.", repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, new RecordItemIndex(9));
            repo.MyHafelePortal.DeliveryAddress_CompanyName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CompanyName' with focus on 'MyHafelePortal.DeliveryAddress_CompanyName'.", repo.MyHafelePortal.DeliveryAddress_CompanyNameInfo, new RecordItemIndex(10));
            repo.MyHafelePortal.DeliveryAddress_CompanyName.PressKeys(CompanyName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_AddressLine1' at Center.", repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, new RecordItemIndex(11));
            repo.MyHafelePortal.DeliveryAddress_AddressLine1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine1' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine1'.", repo.MyHafelePortal.DeliveryAddress_AddressLine1Info, new RecordItemIndex(12));
            repo.MyHafelePortal.DeliveryAddress_AddressLine1.PressKeys(AddressLine1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_AddressLine2' at Center.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(13));
            repo.MyHafelePortal.DeliveryAddress_AddressLine2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine1' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine2'.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(14));
            repo.MyHafelePortal.DeliveryAddress_AddressLine2.PressKeys(AddressLine1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_AddressLine2' at Center.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(15));
            repo.MyHafelePortal.DeliveryAddress_AddressLine2.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AddressLine2' with focus on 'MyHafelePortal.DeliveryAddress_AddressLine2'.", repo.MyHafelePortal.DeliveryAddress_AddressLine2Info, new RecordItemIndex(16));
            repo.MyHafelePortal.DeliveryAddress_AddressLine2.PressKeys(AddressLine2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_TownCity' at Center.", repo.MyHafelePortal.DeliveryAddress_TownCityInfo, new RecordItemIndex(17));
            repo.MyHafelePortal.DeliveryAddress_TownCity.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Town_City' with focus on 'MyHafelePortal.DeliveryAddress_TownCity'.", repo.MyHafelePortal.DeliveryAddress_TownCityInfo, new RecordItemIndex(18));
            repo.MyHafelePortal.DeliveryAddress_TownCity.PressKeys(Town_City);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_County' at Center.", repo.MyHafelePortal.DeliveryAddress_CountyInfo, new RecordItemIndex(19));
            repo.MyHafelePortal.DeliveryAddress_County.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$County' with focus on 'MyHafelePortal.DeliveryAddress_County'.", repo.MyHafelePortal.DeliveryAddress_CountyInfo, new RecordItemIndex(20));
            repo.MyHafelePortal.DeliveryAddress_County.PressKeys(County);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.DeliveryAddress_Postcode' at Center.", repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, new RecordItemIndex(21));
            repo.MyHafelePortal.DeliveryAddress_Postcode.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Postcode' with focus on 'MyHafelePortal.DeliveryAddress_Postcode'.", repo.MyHafelePortal.DeliveryAddress_PostcodeInfo, new RecordItemIndex(22));
            repo.MyHafelePortal.DeliveryAddress_Postcode.PressKeys(Postcode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.AddDeliveryAddressButton' at Center.", repo.MyHafelePortal.AddDeliveryAddressButtonInfo, new RecordItemIndex(23));
            repo.MyHafelePortal.AddDeliveryAddressButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'MyHafelePortal'.", repo.MyHafelePortal.SelfInfo, new RecordItemIndex(24));
            repo.MyHafelePortal.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
