///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Material_Oak recording.
    /// </summary>
    [TestModule("c9c2eb17-58f4-44c3-9dea-bb2d5511885d", ModuleType.Recording, 1)]
    public partial class Material_Oak : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static Material_Oak instance = new Material_Oak();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Material_Oak()
        {
            Thickness = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Material_Oak Instance
        {
            get { return instance; }
        }

#region Variables

        string _Thickness;

        /// <summary>
        /// Gets or sets the value of variable Thickness.
        /// </summary>
        [TestVariable("09f51953-685e-48da-83d4-4fd289525884")]
        public string Thickness
        {
            get { return _Thickness; }
            set { _Thickness = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Material_Oak' at Center.", repo.MyHafelePortal.Material_OakInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.Material_Oak.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.SelectThickness' at Center.", repo.MyHafelePortal.SelectThicknessInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.SelectThickness.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '16{Return}' with focus on 'MyHafelePortal.SelectThickness'.", repo.MyHafelePortal.SelectThicknessInfo, new RecordItemIndex(2));
            repo.MyHafelePortal.SelectThickness.PressKeys("16{Return}");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Name to '' on item 'MyHafelePortal.Copy_of_MaterialThickness_16mm'.", repo.MyHafelePortal.Copy_of_MaterialThickness_16mmInfo, new RecordItemIndex(3));
            //repo.MyHafelePortal.Copy_of_MaterialThickness_16mm.Element.SetAttributeValue("Name", "");
            //Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MyHafelePortal.Copy_of_MaterialThickness_16mm'.", repo.MyHafelePortal.Copy_of_MaterialThickness_16mmInfo, new RecordItemIndex(4));
                Validate.Exists(repo.MyHafelePortal.Copy_of_MaterialThickness_16mmInfo, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MyHafelePortal.Copy_of_MaterialThickness_16mm'.", repo.MyHafelePortal.Copy_of_MaterialThickness_16mmInfo, new RecordItemIndex(5));
            //repo.MyHafelePortal.Copy_of_MaterialThickness_16mm.EnsureVisible();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Copy_of_MaterialThickness_16mm' at Center.", repo.MyHafelePortal.Copy_of_MaterialThickness_16mmInfo, new RecordItemIndex(6));
            //repo.MyHafelePortal.Copy_of_MaterialThickness_16mm.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
