///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HUKBespokeTimberDrawers
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MyHafele_Save_Product_And_Exit recording.
    /// </summary>
    [TestModule("32a18fd9-489f-4d0d-9261-04ba7897f222", ModuleType.Recording, 1)]
    public partial class MyHafele_Save_Product_And_Exit : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HUKBespokeTimberDrawersRepository repository.
        /// </summary>
        public static HUKBespokeTimberDrawersRepository repo = HUKBespokeTimberDrawersRepository.Instance;

        static MyHafele_Save_Product_And_Exit instance = new MyHafele_Save_Product_And_Exit();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MyHafele_Save_Product_And_Exit()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MyHafele_Save_Product_And_Exit Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.SaveProductAndExit' at Center.", repo.MyHafelePortal.SaveProductAndExitInfo, new RecordItemIndex(0));
            repo.MyHafelePortal.SaveProductAndExit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'MyHafelePortal'.", repo.MyHafelePortal.SelfInfo, new RecordItemIndex(1));
            repo.MyHafelePortal.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.BackLink_Arrow' at Center.", repo.MyHafelePortal.BackLink_ArrowInfo, new RecordItemIndex(2));
            //repo.MyHafelePortal.BackLink_Arrow.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Draft_Badge_Button' at Center.", repo.MyHafelePortal.Draft_Badge_ButtonInfo, new RecordItemIndex(3));
            //repo.MyHafelePortal.Draft_Badge_Button.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MyHafelePortal.Draft_EditButton' at Center.", repo.MyHafelePortal.Draft_EditButtonInfo, new RecordItemIndex(4));
            //repo.MyHafelePortal.Draft_EditButton.Click();
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
